### ISSUE TITLE
Suspend issue - just fixed half way

### ISSUE THREAD

**Issue by MichaelBrauner** [longsleep/t14g3amd-linux#1]
Hello Simon, 

I am very happy to see that you have similar issues like me. 
But I think you are a huge bunch more Linux savy than me. 

After your fix for the suspend issue my T14 don't panics anymore because of the hanging applications. 

BUT I have to reactivate WiFi every time manually. Even If I just open & close the lid for a short amount of time. 

It seams so the WiFi is not getting reactivated properly. 

Do you have an idea what I can try to make this work?

**Comment by longsleep** [comment]
Hi Michael,

if you follow the instructions in https://github.com/longsleep/t14g3amd-linux#fixing-suspend there are two scripts added. The first one disables wifi before suspend, while the second one reenables it after resume.

This works fine for me always. I suggest you double check that you have really added both scripts.

Cheers
Simon

**Comment by MichaelBrauner** [comment]
Thank you for the fast answer. 

I have the following script in `/usr/lib/systemd/system-sleep/99-t14-g3-amd-resume-fix`

```bash
case $1 in
    # This always unblocks wifi, even if it was blocked before, can be improved
    # later on.
    post) rfkill unblock wifi ;;
esac        
```

In my case this does apparently nothing. 
Do you have an idea what this might be?

**Comment by longsleep** [comment]
> I have the following script in `/usr/lib/systemd/system-sleep/99-t14-g3-amd-resume-fix`

Mhm if that does not work, then i don't have an idea really. Make sure you have made it executable too and that your distro does actually have those hooks functional.

Their execution gets logged into the journal. Look at the log like this `journalctl -f -n 100 -u systemd-suspend.service`. Looks like this

```
Dez 08 13:55:19 mose4 systemd[1]: Starting System Suspend...
Dez 08 13:55:29 mose4 systemd-sleep[33409]: Entering sleep state 'suspend'...
Dez 08 13:56:05 mose4 systemd-sleep[34206]: + rfkill unblock wifi
Dez 08 13:56:05 mose4 systemd-sleep[33409]: System returned from sleep state.
Dez 08 13:56:06 mose4 systemd[1]: systemd-suspend.service: Deactivated successfully.
Dez 08 13:56:06 mose4 systemd[1]: Finished System Suspend.
```

**Comment by MichaelBrauner** [comment]
It works perfect now. 
I forgot the shebang.

Sorry for my noobieness.  
And thank you very much for your help!
